[colors.primary]
background = "#ffffff"
foreground = "#2e2d31"

[colors.normal]
blue    = "#267aa3"
cyan    = "#5ecbce"
green   = "#24d998"
magenta = "#ff88d6"
red     = "#cc2443"
yellow  = "#d0b56a"
white   = "#fefcf4"
black   = "#2e2d31"

[env]
TERM = "xterm-256color"

[font]
size = 7
