[colors.bright]
black = "0x654735"
blue = "0x45707a"
cyan = "0x4c7a5d"
green = "0x6c782e"
magenta = "0x945e80"
red = "0xc14a4a"
white = "0xeee0b7"
yellow = "0xb47109"

[colors.normal]
black = "0x654735"
blue = "0x45707a"
cyan = "0x4c7a5d"
green = "0x6c782e"
magenta = "0x945e80"
red = "0xc14a4a"
white = "0xeee0b7"
yellow = "0xb47109"

[colors.primary]
background = "0xe2f1c7"
foreground = "0x654735"

[env]
TERM = "xterm-256color"

[font]
size = 8

[font.bold]
family = "Input Mono"
style = "Medium"

[font.bold_italic]
family = "Input Mono"
style = "Medium Italic"

[font.italic]
family = "Input Mono"
style = "Light Italic"

[font.normal]
family = "Input Mono"
style = "Light"

[window.padding]
x = 2
y = 2
