#!/usr/bin/env zsh

# enable vim mode
bindkey -v
export KEYTIMEOUT=1

# open vim to edit the commandline
# https://stackoverflow.com/a/903973
autoload -Uz edit-command-line; zle -N edit-command-line
bindkey -M vicmd 'v' edit-command-line

bindkey -M viins '^A'     vi-beginning-of-line
bindkey -M viins '^E'     vi-end-of-line
bindkey -M viins '\e[P'   delete-char               # <DEL>
bindkey -M viins '\e[H'   vi-beginning-of-line      # <HOME>
bindkey -M viins '\e[4~'  vi-end-of-line            # <END>

# use strg + ` hjkl` keys to move inside the menu
bindkey -M menuselect '^h' vi-backward-char
bindkey -M menuselect '^k' vi-up-line-or-history
bindkey -M menuselect '^l' vi-forward-char
bindkey -M menuselect '^j' vi-down-line-or-history

# enable vim surround like keymaps
autoload -Uz surround
zle -N delete-surround surround
zle -N add-surround surround
zle -N change-surround surround
bindkey -M vicmd cs change-surround
bindkey -M vicmd ds delete-surround
bindkey -M vicmd ys add-surround
