#!/bin/bash

pgrep -x sxhkd -u $UID >/dev/null && kill -USR1 $(pgrep -u $UID sxhkd) || sxhkd &
pgrep -x dunst -u $UID >/dev/null || dunst &

if (( $(bspc query -D | wc -l) < 10)); then
    bspc desktop -d 01 02 03 04 05 06 07 08 09 00
fi

bspc config border_width 3
bspc config window_gap 5
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

# Colors
bspc config normal_border_color "#eeeeee"
bspc config focused_border_color "#555555"

# Rules
bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a Zathura state='tiled'
bspc rule -a Surf state='tiled'
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a mpv state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
