directory: ~/audio/files
# library: ~/audio/library.db
library: ~/.config/beets/library.db
log: ~/audio/.log

import:
  move: yes
  copy: yes

plugins: edit fetchart embedart discogs

  # pathname options
asciify_paths: yes

replace:
  '["]': ''
  "[']": ''
  '[!\?\|\*:<>,.]': ''
  '[ ]': _

paths:
  default: %lower{$albumartist/$album/${track}-${artist}-${title}}
  comp: %lower{various/$album/${track}-${artist}-${title}}
  # singleton: %lower{singleton/$albumartist/$album/${track}-${artist}-${title}}



musicbrainz:
  extra_tags: [year, catalognum, country, media, label]
